internal_name: llama-api-4-maverick
provider: llama
pricing:
  input: 0
  output: 0
  cache_read: 0
  cache_write: 0
aliases:
  - Llama-4-Maverick-17B-128E-Instruct-FP8
provider_slugs:
  llama: Llama-4-Maverick-17B-128E-Instruct-FP8

agent_specific:
  opencode:
    provider_name: llama
